"""delete language to posts

Revision ID: 556ebe2d577f
Revises: ef1b7aff6f58
Create Date: 2021-01-25 14:16:18.427535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556ebe2d577f'
down_revision = 'ef1b7aff6f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    # ### end Alembic commands ###
